### ISSUE TITLE
Task Deletion Upon Changing Task Name during Synchronization

### ISSUE THREAD

**Issue by imsherl** [casmith/sync-todoist-to-habitica#23]
# Description:
When attempting to change the name of a task and subsequently syncing it after the initial synchronization, we encounter an issue where the task is automatically deleted during the update process.

# Steps to Reproduce:
1. Perform an initial synchronization of tasks.
2. Select a task.
3. Change the task's name.
4. Initiate a sync operation.
5. Observe that the task is deleted upon synchronization.

# Expected Behavior:
The task's name should be updated without any unintended deletion during the synchronization process.

# Actual Behavior:
The task is deleted when its name is changed and then synchronized.

# Additional Information:
This issue disrupts our workflow and can lead to data loss. Please investigate and address this matter promptly.

# Related Image Part
That was the name of the task when I first synchronized:
![image](https://github.com/casmith/sync-todoist-to-habitica/assets/142403502/7497f689-3edf-4f53-af2e-5eae2a82b069)
The output when I change the name of the task:
![image](https://github.com/casmith/sync-todoist-to-habitica/assets/142403502/960d7b6f-ce4f-42e2-a70c-b86dc3e63200)

Have a wonderful day!
Best regards,
Imsherl

**Comment by casmith** [comment]
@imsherl can you please pull the latest image and try again?
